'------------------------------------------------------------------------------
' <auto-generated>
'     O código foi gerado por uma ferramenta.
'     Versão de Tempo de Execução:4.0.30319.42000
'
'     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
'     o código for gerado novamente.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=4.6.1055.0.
'

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.Web.Services.WebServiceBindingAttribute(Name:="NFeInutilizacao4Soap12", [Namespace]:="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4")>  _
Partial Public Class NFeInutilizacao4
    Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
    
    Private nfeInutilizacaoNFOperationCompleted As System.Threading.SendOrPostCallback
    
    '''<remarks/>
    Public Sub New()
        MyBase.New
        Me.SoapVersion = System.Web.Services.Protocols.SoapProtocolVersion.Soap12
        Me.Url = "https://nfe-homologacao.sefazrs.rs.gov.br/ws/nfeinutilizacao/nfeinutilizacao4.asm"& _ 
            "x"
    End Sub
    
    '''<remarks/>
    Public Event nfeInutilizacaoNFCompleted As nfeInutilizacaoNFCompletedEventHandler
    
    '''<remarks/>
    <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4/nfeInutilizacaoNF", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Bare)>  _
    Public Function nfeInutilizacaoNF(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4")> ByVal nfeDadosMsg As System.Xml.XmlNode) As <System.Xml.Serialization.XmlElementAttribute("nfeResultMsg", [Namespace]:="http://www.portalfiscal.inf.br/nfe/wsdl/NFeInutilizacao4", IsNullable:=true)> System.Xml.XmlNode
        Dim results() As Object = Me.Invoke("nfeInutilizacaoNF", New Object() {nfeDadosMsg})
        Return CType(results(0),System.Xml.XmlNode)
    End Function
    
    '''<remarks/>
    Public Function BeginnfeInutilizacaoNF(ByVal nfeDadosMsg As System.Xml.XmlNode, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
        Return Me.BeginInvoke("nfeInutilizacaoNF", New Object() {nfeDadosMsg}, callback, asyncState)
    End Function
    
    '''<remarks/>
    Public Function EndnfeInutilizacaoNF(ByVal asyncResult As System.IAsyncResult) As System.Xml.XmlNode
        Dim results() As Object = Me.EndInvoke(asyncResult)
        Return CType(results(0),System.Xml.XmlNode)
    End Function
    
    '''<remarks/>
    Public Overloads Sub nfeInutilizacaoNFAsync(ByVal nfeDadosMsg As System.Xml.XmlNode)
        Me.nfeInutilizacaoNFAsync(nfeDadosMsg, Nothing)
    End Sub
    
    '''<remarks/>
    Public Overloads Sub nfeInutilizacaoNFAsync(ByVal nfeDadosMsg As System.Xml.XmlNode, ByVal userState As Object)
        If (Me.nfeInutilizacaoNFOperationCompleted Is Nothing) Then
            Me.nfeInutilizacaoNFOperationCompleted = AddressOf Me.OnnfeInutilizacaoNFOperationCompleted
        End If
        Me.InvokeAsync("nfeInutilizacaoNF", New Object() {nfeDadosMsg}, Me.nfeInutilizacaoNFOperationCompleted, userState)
    End Sub
    
    Private Sub OnnfeInutilizacaoNFOperationCompleted(ByVal arg As Object)
        If (Not (Me.nfeInutilizacaoNFCompletedEvent) Is Nothing) Then
            Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
            RaiseEvent nfeInutilizacaoNFCompleted(Me, New nfeInutilizacaoNFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
        End If
    End Sub
    
    '''<remarks/>
    Public Shadows Sub CancelAsync(ByVal userState As Object)
        MyBase.CancelAsync(userState)
    End Sub
End Class

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")>  _
Public Delegate Sub nfeInutilizacaoNFCompletedEventHandler(ByVal sender As Object, ByVal e As nfeInutilizacaoNFCompletedEventArgs)

'''<remarks/>
<System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0"),  _
 System.Diagnostics.DebuggerStepThroughAttribute(),  _
 System.ComponentModel.DesignerCategoryAttribute("code")>  _
Partial Public Class nfeInutilizacaoNFCompletedEventArgs
    Inherits System.ComponentModel.AsyncCompletedEventArgs
    
    Private results() As Object
    
    Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
        MyBase.New(exception, cancelled, userState)
        Me.results = results
    End Sub
    
    '''<remarks/>
    Public ReadOnly Property Result() As System.Xml.XmlNode
        Get
            Me.RaiseExceptionIfNecessary
            Return CType(Me.results(0),System.Xml.XmlNode)
        End Get
    End Property
End Class
